### ISSUE TITLE
Race in createGuest

### ISSUE THREAD

**Issue by andylash** [artwells/meteor-accounts-guest#15]
That call to Meteor.users.find().count() to set the guest name won't work reliably.  That code will yield on the server, so it might have changed by the time you do the insert below.  And thus you might try to insert 2 with the same count.  I think using a Random value in the guest name would be more robust.

**Comment by artwells** [comment]
https://github.com/artwells/meteor-accounts-guest/releases/tag/1.4.1 resolves this
