### ISSUE TITLE
Cannot login with useraccounts package

### ISSUE THREAD

**Issue by buduguru** [artwells/meteor-accounts-guest#17]
I use `useraccounts` pkg for signin/signup forms. When I add `accounts-guest` pkg the forms just disappear as happens if user is logged in normally. So, the problem is that the `useraccounts` considers guest user as logged-in user. Should I ask it in its repo or you can help? Thank you in advance.

I posted the same issue in `useraccounts` repo here https://github.com/meteor-useraccounts/core/issues/280

**Comment by artwells** [comment]
I can probably add something to account for useraccounts.  It'll take a week or two though.

**Comment by buduguru** [comment]
Ok, will try it again if you solve it. Thank you.

**Comment by artwells** [comment]
Sounds like the recommendation in https://github.com/meteor-useraccounts/core/issues/223 would be the way to go.  I don't think there's much I can do with accounts-guest without messing up useraccounts behavior.

**Comment by buduguru** [comment]
@artwells ok, I will try that workaround. thank you
