### ISSUE TITLE
dependecy

### ISSUE THREAD

**Issue by KristerV** [artwells/meteor-accounts-guest#23]
if your package doesn't work without 

meteor add accounts-base
meteor add accounts-password

then add them add dependencies.

thanks

**Comment by artwells** [comment]
Removed the unnecessary lines from README in 0.1.9

Thanks

**Comment by KristerV** [comment]
are they unnecessary? I tried the plugin and it didn't work without these. Perhaps I did something else wrong.

**Comment by artwells** [comment]
They should be unnecessary. I've confirmed on a fresh project that accounts-guest and accounts-password are installed along with artwells:accounts-guest.

$ meteor add artwells:accounts-guest
                                              
Changes to your project's package version selections:
                                              
accounts-base            added, version 1.2.0 
accounts-password        added, version 1.1.1
artwells:accounts-guest  added, version 0.1.9
email                    added, version 1.0.6
localstorage             added, version 1.0.3
npm-bcrypt               added, version 0.7.8_2
service-configuration    added, version 1.0.4
sha                      added, version 1.0.3
srp                      added, version 1.0.3

**Comment by KristerV** [comment]
right. I guess this issue is solved then. thanks.

**Comment by artwells** [comment]
thanks
