### ISSUE TITLE
Login Token Clean Up

### ISSUE THREAD

**Issue by Zodiase** [artwells/meteor-accounts-guest#31]
Currently when a guest signs in with username and password, the old login token for the guest account won't get deleted as if the guest signs out.
This might not be a big problem since all guest accounts are going to be cleaned up at some point, but I just think it's a good feature to have. :)

**Comment by artwells** [comment]
I had considered that as a feature, but wanted to keep such clean-up actions as back-end only operations, not part of the user's experience.  I'm thinking of something placed in a work queue.

**Comment by artwells** [comment]
does https://github.com/artwells/meteor-accounts-guest/pull/34 resolve this?

**Comment by artwells** [comment]
reopen if it doesn't
