### ISSUE TITLE
Reuse Guest Accounts?

### ISSUE THREAD

**Issue by Zodiase** [artwells/meteor-accounts-guest#32]
Say a user visits the site and gets a new guest account. Then he/she creates a member account and automatically got signed in. Now that guest account created for him/her is abandoned. When the user signs out before that guest account expires, would it be nice to be able to reuse that guest account?
What worries me right now is that by executing `Meteor.logout()` in the console I could easily fill the `users` collection with lots of guest accounts that will never be used.

**Comment by artwells** [comment]
Here again, some cleaning process should be placed in back-end queued work.  I'd rather not have something that would, when a user logs in, cleans out the old guest account while the user waits.

**Comment by artwells** [comment]
Does https://github.com/artwells/meteor-accounts-guest/pull/34 resolve this?

**Comment by artwells** [comment]
reopen if not
