### ISSUE TITLE
Anonymous users can't register since 0.1.13

### ISSUE THREAD

**Issue by RazZziel** [artwells/meteor-accounts-guest#41]
Before my last meteor upgrade (https://clbin.com/Zo0E9, Meteor 1.1.0.2 -> 1.2.0.1, artwells:accounts-guest 0.1.12 -> 0.1.13, anonymous accounts worked as expected:
* Every new user got a new Meteor.userId()
* They were still shown the "Sign in / Join" button
* They could login whenever they pleased

After this upgrade:
* Every new user gets a new Meteor.userId()
* They're **not** shown the "Sign in / Join" button
** Instead, either a made-up username or an empty username is shown, depending on AccountsGuest.anonymous and AccountsGuest.name
* Instead of registration and signup options, the user is only presented with the option to sign out, but when he signs out, a new anonymous account is automatically created again, so he never gets the chance to register

**Comment by RazZziel** [comment]
Btw, this should be enough to reproduce the bug:
```
git clone git@github.com:RazZziel/LetsGO.git
cd LetsGO
meteor
```
(anonymous users can register)
```
<Ctrl+C>
meteor update
meteor
```
(anonymous users now **can't** register)

**Comment by RazZziel** [comment]
Also reproducible after upgrading only `accounts-guest` package with:
```
$ meteor update artwells:accounts-guest
                                                                                   
Changes to your project's package version selections from updating package versions:
                                              
accounts-password             removed from your project
artwells:accounts-guest       upgraded from 0.1.12 to 0.1.13
brettle:accounts-login-state  added, version 0.0.3
brettle:accounts-patch-ui     added, version 0.0.1
npm-bcrypt                    removed from your project
sha                           removed from your project
srp                           removed from your project
```
diff: https://clbin.com/9yHYJ

I also managed to update meteor while keeping accounts-guest package working:

```
$ meteor remove artwells:accounts-guest
$ meteor add artwells:accounts-guest@=0.1.12
$ meteor update
```
diff: https://clbin.com/P6T5l

**Comment by MastaBaba** [comment]
I encountered the same problem. Moving back to version 0.1.12 seems to prevent the issue from happening.

**Comment by artwells** [comment]
@brettle can you look into this, seems to be your pull request remvoed some funcitonality

**Comment by brettle** [comment]
Looking into it...

**Comment by brettle** [comment]
I think I've found the problem. My PR changed things so that instead of replacing the `currentUser` helper globally, it is uses `brettle:accounts-patch-ui` which only overrides `currentUser` in `Template.loginButtons` _and_ (this is the relevant bit) only when `accounts-ui-unstyled` is installed. You are using `ian:accounts-ui-bootstrap-3` which provides it's own `Template.loginButtons` and doesn't use `accounts-ui-unstyled`, so `brettle:accounts-patch-ui` doesn't override `currentUser` in the `loginButtons` template and you don't get the Sign in/up option.

I'm currently trying figure out the best way to fix it.

**Comment by brettle** [comment]
This should be fixed now for users of `ian:accounts-ui-bootstrap-3`. A `meteor update` should update their `brettle:accounts-patch-ui` to version 0.1.2 which I just published and which adds support for that package. 

@RazZziel, please confirm that this fixes things for you. 

@MastaBaba, if a `meteor update` doesn't fix this for you, please indicate what accounts UI package you are using.

@artwells, `brettle:accounts-patch-ui` only supports packages which use `accounts-ui-unstyled` (e.g. `accounts-ui`), the `useraccounts` suite, and now `ian:accounts-ui-bootstrap-3`. Your README currently claims support for "any other accounts-ui derivative". If the derivative uses `accounts-ui-unstyled`, it should work. Other "derivatives" which actually replace `accounts-ui-unstyled` (like `ian:accounts-ui-bootstrap-3`) will not work unless support for them is explicitly added. You could return to overriding the global `currentUser` helper if you want complete backward compatibility and are willing to accept that such an override has effects outside of the login buttons. The following code should do that:

```js
Template.registerHelper("currentUser", 
  AccountsPatchUi.wrapWithSignedUp(function () {
    return Meteor.user();
  })
);
```

**Comment by RazZziel** [comment]
Last `meteor update` pushed iron:router from 1.0.9 to 1.0.10, so now I can't update brettle:accounts-patch-ui because of this dependency:
```
iron:router@=1.0.9 <- brettle:accounts-patch-ui 0.1.2 <- artwells:accounts-guest 0.1.13
```

**Comment by brettle** [comment]
Fixed now. Please try again. Thanks!

**Comment by MastaBaba** [comment]
Seems to be working for me.

**Comment by RazZziel** [comment]
After running `meteor update`, social login buttons are shown, but user/password login is not.
After realizing the `accounts-password` had been removed and reinstalling it, everything seems to be running fine again.
