### ISSUE TITLE
Meteor.userId() is null.

### ISSUE THREAD

**Issue by Rajan** [artwells/meteor-accounts-guest#44]
Is there a way to fix this?
I tried this syntax but it's throwing javascript errors on the browsers.. Meteor:userId().

**Comment by Rajan** [comment]
<img width="669" alt="screen shot 2015-10-14 at 9 57 26 pm" src="https://cloud.githubusercontent.com/assets/60307/10490459/d021367e-72be-11e5-9080-9f8fccd50a11.png">

**Comment by Rajan** [comment]
I used some other package now.

**Comment by gemhuang21519992** [comment]
recommendation on the package you are using ?
