### ISSUE TITLE
Not compatible with Meteor 1.2?

### ISSUE THREAD

**Issue by KnutSv** [artwells/meteor-accounts-guest#45]
After updating Meteor to 1.2 {{currentUser}} no longer works, and users are not assigned random usernames and emails

**Comment by artwells** [comment]
It seems to be working here.  When updating to Meteor 1.2 some packages may be removed.  Please check to see you have accounts-password etc installed

**Comment by Goatic** [comment]
works just fine in 1.2 for me. Make sure to satisfy package dependencies, though.

**Comment by artwells** [comment]
re-open if still a problem
